 version: 2
 jobs:
  build:
    docker:
      - image: cypress/base:12.6.0
    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-

      - run: npm install

      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/node_modules

      - run: ./node_modules/.bin/eslint --parser-options=sourceType:module --env 'es6' cypress/ gulpfile.js
      - run: ./node_modules/.bin/eslint enrollment.js

      - run: npm run cypress